#Counting DNA Nucleotides

dna = "AGATGAAGTAATCAAAATAGCACCGTAACACANTGGGGCTTACTATATCGCCGGGCAATGTAGTTGGCCTCAGGTAAGGGAGCGCTCAAGAATTTGGTCCACTAACCCTATAATGGGACCCGCGGGTCCAAACTAATAGGAGCTATAGTTCGATTGTAATCGTCTATCCCGGTTGTCCATCGTTATTAGGTAGCGTAAGTGAGACGCCTAGTTTACGGCCGACCGCGGAGCCCCAGAGCATTGGAACTGTCTACTATAAAATACTGAAACCTAGGCTACCAGCTTGCACTACCTATCATCGCTTTCGCTCCTTCGCATGGCGCTTGTAATGCCAGTCGTAATATTAGGGGACCGTAATAGATTGGAGTCGATGAGTCTTGTATAGCCCCCTGATTTCGGAAAGCTTCCCTGATCTAGCAAACTATAGTCTAGTAGAATGGCCCGCTTGCGAGATGTCACGATTAATGAACTTTTGGGTAAGTAACAAGCTGATGCGAATAATCGGCCAGTZGATGAGTAACGATTATATGCTYGAGAGCGATCCCGCAGCTCCTAAACAGGTGTACCGATTACCCCCAGCTGCTGGGTTACATTGAGGAGTTATCCAAAATCAGCGCCCTCGCAAAAAGGGTGCTCTGCTTGTAAGTATGACAAACTGGTACAGCTCAACGACGATTAGACGACGTTGCCCGGAGGCTGGAAATCACAATCAGAACTATCTGGAACTCTGAGTCAGAGCGCCGTCCCTTAGCACTGGTTCCAAAGGCCCTACGTCAAGCCATGCCTTGCTTCGCTTTCAAGTTTCTGGAGGGCGGTCGGGCTGCGACTCCAAATTTGGATCGACATGGTTCAGCTGAAGGGAGATGCCACGCTGGCCGCGGCATAAAATGAATACCTCGTACACACATCACTTACGCAAGCGTCCTTCAGGTGCTCTAGTCTGCATCCTGTAAA"

aCount = 0
gCount = 0
cCount = 0
tCount = 0

for i in range(0,len(dna)):
  if dna[i]=="A":
    aCount = aCount + 1
  elif dna[i]=="G":
    gCount = gCount + 1
  elif dna[i]=="C":
    cCount = cCount + 1
  elif dna[i]=="T":
    tCount = tCount + 1
  else:
    print("ERROR invalid nucleobase: "+dna[i])

print(str(aCount) +" "+ str(cCount)+" "+str(gCount)+" "+str(tCount))
