#Finding a Motif in DNA

s = 'TAGTATAAATGTCGCTAGTATAAATTCTGTGCAGTATAAAGAGTATAAATTGTATAAACGTATAAAGAGTATAAAGTATAAATGTATAAAGGTATAAAGTTCGGTATAAATTGGTATAAAAGGTAAGTATAAAGTATAAAGATGCAGTATAAACTGATATGGTATAAAGTATAAAGTATAAACATCCATGTCACGTATAAATGGAGAGTATAAAGTGTATAAATGTCAGTATAAATGGCGTATAAATCGAAGTATAAAGCGTATAAAGTATAAACTGTATAAATTGTATAAACGGTATAAACGTTTCGTATAAACTGAGTATAAAAGTATAAAGGTATAAAGTATAAAAAAGGGTATAAAGTATAAACGTGTGTATAAAGTACGCATAGGGCGTATAAAGTATAAAATGTATAAAGCAGTATAAATCGGTATAAACGTCTGCGTATAAAAGAGACGTATAAAGTATAAATTTTCGGTATAAAGGTATAAATGGGTATAAAGTCAGTATAAATAGTATAAAGTATAAAAAGACGTATAAAGTATAAAGTATAAAGGTATAAAGAAGTTCAGCAGTATAAAGTATAAAGTATAAACGTAGTATAAAAGCCGTATAAATACCCGGGTATAAACGTATAAAGCGTATAAATAGTATAAAGCGTATAAAGTATAAAACCTGGTATAAAGGTGTATAAAGTATAAAAGTATAAATGTATAAACTCAAGTATAAATATATTGGTATAAACTGTATAAAAGTATAAATTGGTATAAAAACGTATAAAGTATAAACAAGTATAAATCTGTATAAAGTATAAATGTATAAACTGATCATTAGTATAAAGCGTATAAATGTATAAACGTATAAA'
t = 'GTATAAAGT'
motifs = []

for i in range(0,len(s)):
    if t[0]==s[i]:
        if t[0:len(t)]==s[i:i+len(t)]:
            motifs.append(i+1)

for i in range(0, len(motifs)):
    motifs[i] = str(motifs[i])
locations = ' '.join(motifs)

print(locations)
