import numpy as np

MODULO_CONSTANT = 1000000


def backwardsCodons():
    return{
    'F':2,
    'L':6,
    'S':6,
    'Y':2,
    'C':2,
    'W':1,
    'P':4,
    'H':2,
    'Q':2,
    'R':6,
    'I':3,
    'M':1,
    'T':4,
    'N':2,
    'K':2,
    'V':4,
    'A':4,
    'D':2,
    'E':2,
    'G':4,
    'Stop':3
    }

protein = '''MLYQNMSSFWAYNPQLECQWWEWMWTTCRIHPPGDNCAKGIKVDGHCNSNHNEMVWIAATCTIWRAFKLTPAQKKGNQMGSFANDGNWAFGFRNVIWWSDDGHHEAFDYHFIHIALRMCCTWTRRPPAKVIENKVLGRFVFFAGYRMKYYFNLVEVKAHFSSCLTWWQHLKFKIGPIHEASIHACPNVVPAVYCGHAQDTRAMWGKNGKRSPWHEYAPHQDMLDLCTDSKVWQKLKIHFDQPREHAMTFCLFPLKDHWKCPEMQTYCFVTNNHVLSLQEYNHNRVIPMVMPFIDDHNICVPYTSNGASDEMCIDTEAYLHQYQRQFIYQPLPMDDRSGCILTQAPNLLWVKKNYDGGTSPMHKYITFHNQHQYMRHATTCTMYMEPQCDTKGEHGCPCCFPGLNRKKSEYHRHAFHNCYVTGLDWMNKLRMLLYWYPFLRIRGYKKLKFHRFQPTEWHYWISEQTAERGTIWQPCLQKLFKCTKQTSHWTAYICFHKECRNGMDPNEQDLGFAGMPHYKDQMLCELEGPYENGRYSGIFWLTCYNPFWDESMELPARQLESPGFRVDHTTKVWHQHDRTECCDAYGLECYSPTKRMGSYQIFQPQGMCLMWQKRNMMMSNYGPEVSVQCSQYKLAEMYGWQLATICKPYVCMKMDTLWFERMYIPYAWQADGTELPNQLGGTQPLCHHMVSGAVDGMSVLMQDDFEQYRYSNHREECQDPKLFQGSTPMDEMSAVPSDSVAKVIIKSYEHQPNRCIRIAPGWLRQGVLHGVNRWMSHGCMWPAEKGFKAQKWFWINKQDDMQASACVGFRSKNRFEGRYNCPLEQCPQQNQMFFAPNDWIKYCERPNKMQKWNYNMTTADVEIHEYSQLSVCICTFEYEYNDTLGKIHLRGQKSSHTGDSFGFLMWGVSRRNMGGIDLCFFMMFMPPAYHGYVNNWHGMVMKEGVEQTGKMDMEKDYWMDDNHQVEKTMDPKCRIRSPYSNNIQRMGFAVSMAQSLV'''
aminoacids = list(protein)
aminoacids.append('Stop')
instances = backwardsCodons()

combinationList = []
total = 1
for i in range(0,len(aminoacids)):
    combinationList.append(instances[aminoacids[i]])
    total = total * combinationList[i]

total = total%MODULO_CONSTANT
print(total)
